name: keepass
base: core20
version: '2.49'
summary: KeePass
description: |
  Easy-to-use password manager for Windows, Linux, Mac OS X and mobile devices.


grade: stable # must be 'stable' to release into candidate/stable channels or 'devel'
confinement: classic   #use classic if all fs required OR if you need local gtk2 theming
# confinement: classic


environment:
  GTK_PATH: $SNAP/lib/gtk-2.0
  GTK_DATA_PREFIX: $SNAP
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
  MONO_CFG_DIR: $SNAP/etc
  MONO_CONFIG: $SNAP/etc/mono/config
  MONO_GAC_PREFIX: $SNAP/usr/lib/mono
  MONO_PATH: "$SNAP/usr/lib/cli/atk-sharp-2.0:$SNAP/usr/lib/cli/gdk-sharp-2.0:$SNAP/usr/lib/cli/glib-sharp-2.0:$SNAP/usr/lib/cli/gtk-sharp-2.0:$SNAP/usr/lib/cli/pango-sharp-2.0"

parts:
  keepass:
    plugin: dump
    source: https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.49/KeePass-2.49.zip/download
    source-type: zip
    stage-packages:
      - mono-runtime

  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - build-essential
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  keepass:
    command: bin/desktop-launch mono $SNAP/KeePass.exe
    # command-chain: [bin/desktop-launch]
    # desktop: opt/keepass/share/applications/bless.desktop
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: "1"
    plugs:
      - network
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
      - x11
      - wayland
      - home
      - removable-media
      - fuse-support
      - system-files

